"""Knowledge Card data model — stores knowledge card agent output per task."""

import uuid
from datetime import datetime

from sqlalchemy import (
    DateTime,
    ForeignKey,
    Integer,
    String,
    Text,
    UniqueConstraint,
    func,
)
from sqlalchemy.dialects.postgresql import JSONB, UUID
from sqlalchemy.orm import Mapped, mapped_column

from app.db.base import Base


class KnowledgeCardData(Base):
    """Knowledge cards generated by the Knowledge Card Agent."""

    __tablename__ = "knowledge_card_data"
    __table_args__ = (
        UniqueConstraint("task_id", name="uq_knowledge_card_task"),
    )

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), primary_key=True, default=uuid.uuid4,
    )
    task_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("disassembly_tasks.id", ondelete="CASCADE"),
        nullable=False,
    )
    material_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("materials.id", ondelete="CASCADE"),
        nullable=False,
    )

    # Content
    cards: Mapped[list] = mapped_column(JSONB, nullable=False)  # list[KnowledgeCard dict]
    formula_sheet: Mapped[str] = mapped_column(Text, nullable=False)  # markdown
    error_taxonomy: Mapped[str] = mapped_column(Text, nullable=False)  # markdown

    # Quality audit
    model_used: Mapped[str] = mapped_column(String(50), nullable=False)
    prompt_version: Mapped[str] = mapped_column(
        String(20), nullable=False, default="cards_v1",
    )
    input_tokens: Mapped[int] = mapped_column(Integer, nullable=False)
    output_tokens: Mapped[int] = mapped_column(Integer, nullable=False)
    latency_ms: Mapped[int] = mapped_column(Integer, nullable=False)
    run_id: Mapped[str] = mapped_column(String(64), nullable=False)

    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), server_default=func.now(),
    )
